# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RecipeAid' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RecipeAid
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'Hippolyte'
  pod 'When'
  pod 'Firebase/Core'
  pod 'Firebase/Analytics'
  pod 'Firebase/Performance'
  pod 'Fabric', '~> 1.10.2'
  pod 'Crashlytics', '~> 3.13.3'

end

target 'RecipeAidTests' do

  pod 'Hippolyte'
  pod 'Cuckoo'
  pod 'When'
  pod 'Firebase/Core'
end
