# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RecipeAid' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RecipeAid
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'Hippolyte'
  pod 'When'

end

target 'RecipeAidTests' do

  pod 'Hippolyte'
  pod 'Cuckoo'
  pod 'When'
end
